### ISSUE TITLE
[Feature Request] Add instructions for pipe output

### ISSUE THREAD

**Issue by marco79cgn** [GioF71/librespot-docker#111]
Actually not really a feature request as this feature is already there. It's just not mentioned in the README. It says for the BACKEND: "Currently possible values are alsa and pulseaudio" whereas `pipe` works also perfectly fine.

**Usecase:** 
Run librespot-docker with pipe ouput, e.g. to forward the audio to projects like [Owntone](https://owntone.github.io/owntone-server/).

**Example:**
One has to use both `--device /path/to/fifo` and `--backend pipe` parameters. 

What I did is mounting the fifo (named `spotipipe`) from the docker host (`/path/to/fifo`) into the container (`/mnt/pipe`) as volume.

`docker-compose.yml:`
```
services:
  librespot:
    image: giof71/librespot:latest
    network_mode: host
    environment:
      - BACKEND=pipe
      - DEVICE=/mnt/pipe/spotipipe
      - BITRATE=320
      - INITIAL_VOLUME=100
      - DEVICE_NAME=SpotiPi
    volumes:
      - /path/to/fifo:/mnt/pipe
```
That's it, really easy. Maybe you could add this to the README. Thx.

**Comment by GioF71** [comment]
Hello, thank you.
Would you like to contribute the change with a pull request? Otherwise I will do it (can't guarantee the ETA though)

**Comment by GioF71** [comment]
Hello, shouldn't the example be:

```services:
  librespot:
    image: giof71/librespot:latest
    network_mode: host
    environment:
      - BACKEND=pipe
      - DEVICE=/mnt/pipe/spotipipe
      - BITRATE=320
      - INITIAL_VOLUME=100
      - DEVICE_NAME=SpotiPi
    volumes:
      - /path/to/fifo:/mnt/pipe/spotipipe
```

so the file mounted to the fifo file used as device?
In your example they are different but from the explaination, it seems they should be the same.
Thank you

**Comment by marco79cgn** [comment]
In my case, it looks like this: 

```
services:
  librespot:
    image: giof71/librespot:latest
    network_mode: host
    environment:
      - BACKEND=pipe
      - DEVICE=/mnt/music/spotpipe
      - BITRATE=320
      - INITIAL_VOLUME=100
      - DEVICE_NAME=Teddify
    volumes:
      - /home/pi/music:/mnt/music
```
So I'm mounting the local music directory (`/home/pi/music`) into the container (`\mnt\music`) and inside this folder there's the fifopipe named `spotipipe`. So I'm referencing/mounting a folder, not a single file. 

I'm using the same folder for Shairport-Sync and in this case, there are two pipes necessary, one for the music and one for the metadata. Unfortunately there is no metadata with librespot.
