### ISSUE TITLE
Connection reset by peer (os error 104)

### ISSUE THREAD

**Issue by yanover** [GioF71/librespot-docker#43]
Hello,

I am trying to deploy this image in a Kubernetes cluster (K3s). The pod is running on a target node, which is a Raspberry Pi 3 with a HIFI-BERRY DAC+ plugged on it.

I have already tested several images but I always get the same error, it must be more related to the configuration than to the image itself. 

I can connect via Spotify-connect, but after a few minutes the music stops and I get the following errors in the logs: 
```
[2022-10-23T14:55:41Z ERROR librespot_playback::player] Unable to load audio item: MercuryError
[2022-10-23T14:55:41Z ERROR librespot_core::session] Connection reset by peer (os error 104)
[2022-10-23T14:55:41Z ERROR librespot_connect::spirc] subscription terminated
[2022-10-23T14:55:41Z WARN  librespot] Spirc shut down unexpectedly
```

And when I open a connection throught Spotify-connect, I very often get : 
```
[2022-10-23T14:48:34Z WARN  librespot_playback::audio_backend::alsa] Error writing from AlsaSink buffer to PCM, trying to recover, ALSA function 'snd_pcm_writei' failed with error 'EPIPE: Broken pipe'
ALSA lib pcm.c:8545:(snd_pcm_recover) underrun occurred
```

I'm not sure if `asound.conf` is used in the image, but here's the configuration file I mount in the pod (`/asound.conf`):
```
pcm.!default {
  type hw card 0
}
ctl.!default {
  type hw card 0
```

And here are the environments variable provided to the container : 
```
env:
  - name: DEVICE_NAME
    value: SPEAKER
  - name: DEVICE
    value: hw:0,0
  - name: DEVICE_TYPE
    value: speaker
  - name: FORMAT
    value: S24
  - name: BITRATE
    value: '320'
  - name: ENABLE_CACHE
    value: 'Y'
  - name: CACHE_SIZE_LIMIT
    value: 3G
```

I've already try to run without the cache. I suspect a PCM buffer problem but I would like your opinion ?

Thank you !
